package com.project.wisatakukulonprogo;

import java.util.ArrayList;

public class DataWisata {
    public static String[][] data = new String[][]{
            {"Kedung Pedut", "Air Terjun Kedung Pedut atau biasa disebut Curug Kedung Pedutberasal dari istilah bahasa Jawa. Curug yang berarti air terjun, kedung berarti kubangan atau kolam, dan pedut berarti kabut. Air Terjun Kedung Pedut merupakan salah satu wisata alam yang di Kulonprogo yang dikenal karena keindahan warna airnya", "Lokasi : Banyunganti, Jatimulyo, Girimulyo, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta","https://cdn.medcom.id/images/content/2019/01/06/972837/HroPAq3sBC.jpg"},
            {"Waduk Sermo", "Waduk Sermo adalah sebuah waduk yang berada di Kabupaten Kulonprogo, Daerah Istimewa Yogyakarta, Indonesia. Waduk ini dibangun mulai tahun 1994 dan diresmikan oleh Presiden Soeharto 20 November 1996","Lokasi : Sremo Lor, Hargowilis, Kokap, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta ", "https://www.pegipegi.com/travel/wp-content/uploads/2018/10/01.-Waduk-Sermo.jpg"},
            {"Wisata Alam Kalibiru", "Kalibiru adalah objek wisata alam yang berada di daerah kabupaten Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta. Tempat wisata ini memiliki tanah bergelombang dan dominan oleh perbukitan dalam area hutan lindung. Wisata Alam yang bertemakan Hutan Kemasyarakatan Kalibiru berada di Perbukitan Menoreh Kulon Progo Yogyakarta, Pada ketinggian 450 mdpl. Hutan tersebut dikelola masyarakat yang berada di darah itu agar tetap terjaga kelestariannya, sehingga hutan ini dapat dijadikan objek wisata alam","Lokasi : Jalan Waduk Sermo, Kokap, Hargowilis, Kalibiru, Hargowilis, Kokap, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta", "https://www.hargatiket.net/wp-content/uploads/2018/10/Harga-Tiket-Kalibiru-Yogyakarta.jpg"},
            {"Taman Sungai Mudal", "Taman Sungai Mudal adalah obyek wisata alam yang terdapat di Kabupaten Kulon Progo, atau sekitar 1 jam dari pusat kota Yogyakarta jika berkendara. Tempat ini berupa kolam pemandian yang airnya selalu nampak jernih dan berwarna toska yang indah.Ekowisata ini diberi nama Taman Sungai Mudal karena air di sini berasal dari mata air Mudal. Serta tampilan sekitar lokasi ini memang dibuat layaknya sebuah taman, dimana orang-orang berkumpul untuk bersenang-senang sembari menikmati pesona alam.","Lokasi : Banyunganti, Jatimulyo, Girimulyo, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta ", "https://civitas.uns.ac.id/ringbasketFMIPA/wp-content/uploads/sites/677/2018/12/Mudal.jpg"},
            {"Pantai Glagah", "Pantai Glagah merupakan primadona di Kulonprogo. Di pantai ini pengunjung dapat bermain kano di laguna, naik motorcross di hamparan pasir besi, memancing di atas tetrapod yang berfungsi sebagai pemecah ombak, hingga memetik buah naga di agrowisata.Selama ini Kabupaten Kulonprogo seringkali terlupa di kalangan wisatawan. Padahal di Kabupaten ini terdapat sebuah pantai yang indah dengan fasilitas yang sangat beragam, Pantai Glagah namanya. Destinasi wisata ini hanya berjarak sekitar 40 km arah barat Yogyakarta, berbatasan dengan Kabupaten Purworejo, Jawa Tengah.Berbeda dengan pantai-pantai di Gunungkidul yang dibatasi bukit karang, tepian Pantai Glagah terlihat sangat panjang tanpa penghalang. Sejauh mata memandang yang terlihat adalah hamparan pasir besi kehitaman. Ombak di Pantai Glagah terbilang cukup besar. Karena itu di kawasan pantai ini dibangun sebuah dermaga panjang dengan tetrapod di kanan kirinya. Tetrapod tersebut berfungsi sebagai pemecah ombak.  Untuk memasuki kawasan wisata Pantai Glagah, wisatawan cukup merogoh kocek sebesar Rp 4.000.","Lokasi : Glagah, Temon, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta ", "https://www.pantainesia.com/wp-content/uploads/2018/03/Pantai-Glagah-680x382.jpg"},
            {"Alun Alun Wates", "Objek Wisata Alun-Alun Wates di Kulon Progo Yogyakarta adalah salah satu tempat wisata yang berada di Kecamatan Wates, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta, Indonesia. Objek Wisata Alun-Alun Wates di Kulon Progo Yogyakarta adalah tempat wisata yang ramai dengan wisatawan pada hari biasa maupun hari liburan. Tempat ini sangat indah dan bisa memberikan sensasi yang berbeda dengan aktivitas kita sehari hari. Objek Wisata Alun-Alun Wates di Kulon Progo Yogyakarta memiliki pesona keindahan yang sangat menarik untuk dikunjungi. Sangat di sayangkan jika anda berada di kota Kulon Progo tidak mengunjungi Objek Wisata Alun-Alun Wates di Kulon Progo Yogyakarta yang mempunyai keindahan yang tiada duanya tersebut. Objek Wisata Alun-Alun Wates di Kulon Progo Yogyakarta sangat cocok untuk mengisi kegiatan liburan anda, apalagi saat liburan panjang seperti libur nasional, ataupun hari libur lainnya. ","Lokasi : Wates, Terbah, Wates, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta ", "https://2.bp.blogspot.com/-U5UJ5Y1QYEo/WV8FPse4R1I/AAAAAAAAcdw/eOPjbhNtd2w1etqx36E9GxUIAAGyWahWgCLcBGAs/s1600/wates1.jpg"},
            {"Perkebunan Teh Nglinggo", "Kebun Teh Nglinggo adalah satu-satunya kebun teh yang berada di Yogyakarta. Sebenarnya kebun teh ini merupakan tempat mata pencaharian penduduk di sekitar Pagerhajo. Kemudian warga mempunyai ide untuk menjadikannya sebagai tempat wisata. Dengan pesona alamnya Kebun Teh Nglinggo menjadi objek wisata yang cukup terkenal di Kulon Progo.Wisata ini menawarkan objek wisata berupa hamparan perkebunan teh dengan luas sekitar 136 hektare di ketinggian 900-1000 mdpl. Di sana pengunjung dapat melihat para pemetik daun teh dan dapat pula ikut memanen daun teh. Jika kurang puas pengunjung juga dapat naik hingga Puncak Kendeng Gunung Kukusan, dan akan dimanjakan dengan pemandangan alam yang memikat mata juga udara sejuk pegunungan yang masih alami."," Lokasi : Nglinggo Barat, Pagerharjo, Samigaluh, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta ", "https://i0.wp.com/dolandolen.com/wp-content/uploads/2018/02/Kebun-Teh-Nglinggo-by-wahyu_sa.jpg?fit=1080%2C825&ssl=1"},
            {"Bukit Wisata Pulepayung", "Pule Payung merupakan salah satu destinasi wisata yang terdapat di Jogja. Tepatnya berada di Dusun Saropati Desa Hargotirto, Kecamatan kokak, kabupaten Kulon Progo. Bisa dikunjungi saat weekend ataupun kala liburan. Dari pusat kota Jogjakarta, perjalanan bisa ditempuh kurang lebih satu jam perjalanan.Untuk menuju ke destinasi wisata ini, perlu berganti kendaraan jika mengendarai mobil besar. Maka dari itulah, jika tidak berombongan ada baiknya untuk naik sepeda motor saja. Jika kamu mengendarai mobil besar, nanti akan ganti dengan jeep. Hal ini disebabkan karena mobil besar belum bisa naik ke lokasi lantaran medan sangat curam dan juga berbahaya.","Lokasi : Soropati, RT.007/RW.003, Clapar 2, Hargotirto, Kokap, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta ", "https://1.bp.blogspot.com/-LIFsiPuQYFE/XAIsXU-xl-I/AAAAAAAABAQ/OyPY5i1KQ0oHRblTood14aleGfJSzMOzACLcBGAs/s1600/liburan%2Bke%2BPule%2Bpayung%2BKulon%2BProgo.jpg"},
            {"Wisata Alam Mangrove Jembatan Api-Api (MJAA)", "Namanya Mangrove Jembatan Api-api (MJAA), diambil dari nama mangrove jenis api-api (Avicennia) yang tumbuh subur di sana. Destinasi ini berada di Desa Jangkaran, desa terluar dari Kulon Progo dan berbatasan dengan Purworejo, Jawa Tengah.Tempat piknik ini berada di poros Kulon Progo-Purworejo. Setelah berkendara 1,5 jam dari pusat Kota Yogyakarta, maka akan ketemu jembatan Sungai Bogowonto, sungai yang memisahkan kedua kota. Ikutilah petunjuk dengan tulisan ‘Mangrove’ yang ada di sekitarnya. Ikuti petunjuk itu, lantas melintasi sawah-sawah, dan sampailah di pintu wisata. Di sana ada dua pilihan, yakni: mangrove Pasir Mendit (MJAA) atau Kadilangu. Keduanya, sama-sama indah.MJAA merupakan obyek wisata bikinan warga dukuh Pasir Mendit-Pasir Kadilangu. Mereka mengombinasikan hutan mini yang ditumbuhi mangrove, anak Sungai Bogowonto yang membelah hutan, tambak-tambak udang jenis vaname, serta pantai selatan yang menghadap laut lepas Samudera Hindia. Seluruh potensi itu terhubung dengan jembatan bambu."," Lokasi : Pasir Mendit, Jangkaran, Temon, Kulon Progo Regency, Special Region of Yogyakarta ", "https://i1.wp.com/dolandolen.com/wp-content/uploads/2018/01/Wisata-Alam-Mangrove-Jembatan-Api-Api-by-annisa_moo.jpg?fit=1080%2C1350&ssl=1"},
            {"Bukit Ngisis, Nglinggo", "Bukit isis kulon progo – menghabiskan akhir pekan di Jogja memang paling enak menuju malioboro, tapi jangan lupa untuk mengunjungi beberapa tempat wisata yang lain. Salah satunya adalah keindahan akan Kulon Progo yang tidak boleh terlewatkan. Kulon Progo menawarkan keindahan alam yang akan memukau mata Anda. Bukit Isis Kulon Progo menjadi salah satu wisata yang akan menyuguhkan keindahan hijaunya perbukitan menoreh.Dinamakan sebagai Bukit Isis karena memang berarti angin sepoi – sepoi dan hawa yang segar (jawa isis = ngisis = segar = sejuk). Dari atas Bukit Isis ini Anda akan disuguhkan hamparan hijaunya alam Kulon Progo, gagahnya beberapa gunung, seperti Gunung Merapi, Gunung Sumbing, dan Gunung Merbabu serta sejuknya semilir angin yang menyentuh kalbu.","Lokasi : Nglinggo Barat, Pagerharjo, Samigaluh, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta ", "https://airport.id/wp-content/uploads/2017/11/2-6921-isis.jpg"},



    };

    public static ArrayList<Wisata> getListData() {
        ArrayList<Wisata> list = new ArrayList<>();
        for (String[] aData : data) {
            Wisata wisata = new Wisata();
            wisata.setName(aData[0]);
            wisata.setDeskripsi(aData[1]);
            wisata.setLokasi(aData[2]);
            wisata.setPhoto(aData[3]);
            list.add(wisata);
        }
        return list;
    }
}
